---
server:
  port: 8800
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/muratji/pluralsight-spring-cloudconfig-wa-tolls.git
#          username: muratji
#          password:
          search-paths:
            - 'station*'